export const SAMPLE = {
  MESSAGE: 'hello',
};

export const BOUND_SHEETS = {
  LESSONS: 'lessons',
};

export const NAMED_RANGES = {
  BOUND_SHEETS: {
    LESSONS: {
      ID: 'LESSONS.ID',
      DATE: 'LESSONS.DATE',
      DAY_OF_WEEK: 'LESSONS.DAY_OF_WEEK',
      START_TIME: 'LESSONS.START_TIME',
      END_TIME: 'LESSONS.END_TIME',
      STORE_NAME: 'LESSONS.STORE_NAME',
      STUDIO_NAME: 'LESSONS.STUDIO_NAME',
      GENRE: 'LESSONS.GENRE',
      LEVEL: 'LESSONS.LEVEL',
      INSTRUCTOR_NAME: 'LESSONS.INSTRUCTOR_NAME',
      NICKNAME: 'LESSONS.NICKNAME',
      IS_WOMAN_ONLY: 'LESSONS.IS_WOMAN_ONLY',
      IS_MAN_ONLY: 'LESSONS.IS_MAN_ONLY',
      URL: 'LESSONS.URL',
      INSTRUCTOR_IMAGE_URL: 'LESSONS.INSTRUCTOR_IMAGE_URL',
    }
  }
};
